add guard to avoid .get() of absent value
ontoportal-lirmm/owlapi_wrapper pull request #5
Opened 2023-05-19 13:32 UTC by RaimiSol

Fix #4 by adding a guard.

2023-05-21 15:42 UTC, jonquet commented
Adding @syphax-bouazzouni to this... maybe we can ask @jvendetti too. 
Not sure about the issue.

2023-05-23 09:01 UTC, syphax-bouazzouni commented
Hi @RaimiSol,

Thanks for this PR; some remarks 

1. You need to give more details about the issue and how you solved it 
Here, the issue was that resources (SKOS or OWL) with no <owl:ontology> clause defined does not parse and raise catched exception in the `addOntologyImports` function.

Your solution is to not call the `addOntologyImports` function if the ontology is anonymous.

2. About the code, you pushed a lot of linting changes (removing whitespace, ...), that are mixed with your real fix.

2023-05-23 09:07 UTC, syphax-bouazzouni requested changes
You need to remove the linting changes

2023-05-23 09:07 UTC, syphax-bouazzouni commented on src/main/java/org/stanford/ncbo/owlapi/wrapper/OntologyParser.java
> +		if (!sourceOnt.getOntologyID().isAnonymous()) {
a better syntax would be this 
```java
        Optional<IRI> sub = sourceOnt.getOntologyID().getOntologyIRI();
        IRI ontologyIRI;

        if(!sub.isPresent()){
            return;
        }
        ...
```

2023-05-24 11:27 UTC, RaimiSol commented
@syphax-bouazzouni thank you for the remarks. I updated the commit based on your suggestions.

2023-05-25 09:02 UTC, syphax-bouazzouni approved these changes

2023-05-25 09:02 UTC, syphax-bouazzouni commented
Great thanks for the contribution.

2023-05-25 09:06 UTC, merged